# inspired by https://github.com/mvdan/github-actions-golang
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
