# inspired by https://github.com/mvdan/github-actions-golang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      GOLANG: ${{ matrix.go }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          env_vars: OS,GOLANG

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32
          only-new-issues: true
